[server]
mode = "debug"
port = "9000"
http_timeout = 60
cache_expired = 24
cache_purged = 60

[database]
db_driver = "postgres"
db_host = "postgres"
db_port = "5432"
db_name = "zot_news"
db_username = "zakir"
db_password = "Zakir123"

[pool]
conn_idle = 10
conn_max = 20
conn_lifetime = 60
