version: '3'

services:
  backend_app:
    container_name: backend_app
    build:
      context: .
    ports:
      - "9000:9000"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - infrastructure
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
    environment:
      - POSTGRES_PASSWORD=Zakir123
      - POSTGRES_USER=zakir
      - POSTGRES_DB=zog_news
    restart: unless-stopped
    networks:
      - infrastructure
    
networks:
  infrastructure:
    driver: bridge

volumes:
  postgres: